language: ruby
cache: bundler
branches:
  only:
  - master
before_install:
- gem install bundler -v 2.0.1
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  repo: ismailmushraf/ismailmushraf.github.io
  provider: pages
  local-dir: ./site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: a05038e6c0260aa8a3e9894c047f5dbf06907c6b
  keep-history: true
  on:
    branch: master