---
title: micoder
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Ismail Musharaf
email: ismailmushraf@gmail.com
description: 'I''m a Tech Evangelist, I Love AI, Deep Learning, Maths, Competitive
  Programming, Web Dev and Much More. Also I love Teaching!!!

'
show_excerpts: false
paginate: 4
paginate_path: "/page:num/"
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag
dash:
  date_format: "%b %-d, %Y"
  disqus:
    shortname: micoder
  social_links:
  - url: http://ismailmushraf.github.io/about-me
    icon: connectdevelop
    color: green
  - url: https://twitter.com/ismailmushraf
    icon: twitter-square
    color: cyan
  - url: https://linkedin.com/in/ismailmushraf
    icon: linkedin
    color: red
  - url: https://github.com/ismailmushraf
    icon: github-square
    color: purple
  show_author: true
  animation_speed: 50
theme: jekyll-dash
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
- liquid-md5
- jekyll/tagging
avatar_source: github
github_username: ismailmushraf
