title: micoder
author: Ismail Musharaf
email: ismailmushraf@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  I'm a Tech Evangelist, I Love AI, Deep Learning, Maths,
  Competitive Programming, Web Dev and Much More. Also I love Teaching!!!
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 3
paginate_path: "/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: ismailmushraf-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: http://ismailmushraf.github.io/about-me
      icon: connectdevelop
      color: green
    - url: https://twitter.com/ismailmushraf
      icon: twitter-square
      color: cyan
    - url: https://linkedin.com/in/ismailmushraf
      icon: linkedin
      color: red
    - url: https://github.com/ismailmushraf
      icon: github-square
      color: purple

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
avatar_source: github
github_username: ismailmushraf